server:
  port: 8088

spring:
  data:
    mongodb:
      uri: mongodb+srv://tai21042004:21042004@shopeeapp.yptanxn.mongodb.net/ShopeeApp?retryWrites=true&w=majority

  mail:
    host: smtp.gmail.com
    port: 587
    username: tai21042004@gmail.com
    password: TranThiThuyTien@200104
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  prefix: api/v1

jwt:
  expiration: 3600
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=